FROM ubuntu:18.04

MAINTAINER Ai Okada <aokada@ncc.go.jp>

RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip

RUN pip3 install plotly numpy pandas
RUN git clone https://github.com/aokad/gcatworkflow_ganttly.git

CMD ["/bin/bash"]
